version: "3"

services:
  wordpress:
    image: "wordpress:${WP_VERSION:-5.9.1}-php${PHP_VERSION:-8.0}-apache"
    ports:
      - "80:80"
    environment:
      VIRTUAL_HOST: "${DOCKER_DEV_DOMAIN:-project.test}"
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG:-false}"
    depends_on:
      - "mysql"
    networks:
      - "front"
      - "back"
    volumes:
      - "wp:/var/www/html:rw"
      - ".:/var/www/html/wp-content/plugins/my-plugin:ro"
  mysql:
    image: "mariadb:10.2"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
            - 'db:/var/lib/mysql'
    networks:
      - "back"

networks:
  front: {}
  back: {}

volumes:
  wp: {}
  db: {}
